/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { JobPosition, Metric, BusinessArea, Milestone, Partner, OfficeAddress } from './types';

export const METRICS: Metric[] = [
  {
    id: 'platforms',
    value: '3',
    label: 'Core Platforms',
    description: 'Facebook, TikTok, and TikTok Shop US driving global interactions.',
  },
  {
    id: 'satisfaction',
    value: '95',
    suffix: '%',
    label: 'Customer Satisfaction',
    description: 'Pristine service quality score maintained across all digital brands.',
  },
  {
    id: 'customers',
    value: '150,000',
    suffix: '+',
    label: 'Happy Customers',
    description: 'Direct-to-consumer relationships built securely across the United States.',
  },
  {
    id: 'products',
    value: '200,000',
    suffix: '+',
    label: 'Products Delivered',
    description: 'Custom products matched to audience aspirations and sent swiftly.',
  },
];

export const PILLARS = {
  vision: {
    title: 'Vision',
    tagline: 'Leading the Cross-Border E-Commerce Revolution',
    description: 'To become the preeminent global leader in cross-border e-commerce. By combining deep technological insights with creative campaign strategy, we aim to transcend traditional physical retail borders and shape a frictionless micro-retail future.',
    bulletPoints: [
      'Establishing a modern, borderless ecosystem that empowers independent designers.',
      'Maximizing efficiency using automated, cloud-hosted logistic integrations.',
      'Sustaining high-velocity execution across US e-commerce platforms.',
    ]
  },
  mission: {
    title: 'Mission',
    tagline: 'Connecting Audiences via Creative Solutions & Quality Goods',
    description: 'To supply global consumers with exceptionally personalized, premium products. Through high-impact content generation, data-driven advertising, and flawless order fulfillment, Qnext delivers high-caliber marketplace connections.',
    bulletPoints: [
      'Empowering consumers to express identity through custom Print-on-Demand designs.',
      'Minimizing carbon footprints by manufacturing on-demand and routing intelligently.',
      'Forging high-trust relationships using localized feedback loop mechanisms.',
    ]
  },
  culture: {
    title: 'Culture',
    tagline: 'Human-First, Constant Agility & Infinite Learning',
    description: 'Our success is driven by the power of our people. We foster an ultra-collaborative, creative environment where failure is treated as an informative scientific variable. We commit to daily micro-improvements and a continuous learning trajectory.',
    bulletPoints: [
      'Human-Centric Workspace: Tailoring physical and mental growth parameters.',
      'Radical Transparencies: Honest communications driving mutual milestones.',
      'Limitless Curiosity: Ongoing support for skills mastery, workshops, and courses.',
    ]
  }
};

export const BUSINESS_AREAS: BusinessArea[] = [
  {
    id: 'pod',
    title: 'Print-on-Demand (POD)',
    iconName: 'Printer',
    description: 'Expressive personalization with zero warehousing overheads. We design, launch, and optimize tailor-made apparel, accessories, and home goods tailored to precise North American buyer personas.',
    details: [
      'High-resolution custom vector layouts generated by experienced visual artists.',
      'Rapid direct-to-garment (DTG) printing technologies via tier-1 US printing facilities.',
      'Niche community marketing targets backed by detailed search analytics datasets.'
    ],
    process: [
      'Audience Search & Sentiment Mapping',
      'Original Graphic Design & Prototyping',
      'Instant US Localized Manufacturing & Dispatch'
    ]
  },
  {
    id: 'dropshipping',
    title: 'Agile Dropshipping',
    iconName: 'Milestone',
    description: 'Frictionless supply-chain distribution. Leveraging modern shipping channels, we discover winning physical products, list them across active US channels, and coordinate express cross-border transit.',
    details: [
      'AI-backed trending product discovery algorithms evaluating US market momentum.',
      'Strict quality checks with strategic logistics units before shipping dispatch.',
      'Optimized pricing matrix integrations delivering outstanding margins and consumer value.'
    ],
    process: [
      'Viral Product Sourcing & Supplier Audit',
      'Frictionless Listing & High-Converting Advertisements',
      'Direct Factory-To-Door Shipping with Full Tracking'
    ]
  },
  {
    id: 'tiktok-shop',
    title: 'TikTok Shop US Operations',
    iconName: 'ShoppingBag',
    description: 'The absolute frontier of modern Social Commerce. We operate highly dynamic virtual storefronts inside the United States TikTok Shop ecosystem, blending native short-form video content with instantaneous in-feed shopping checkouts.',
    details: [
      'Affiliate micro-creator outreach program utilizing vast automated collaboration funnels.',
      'TikTok Shop livestream planning and optimized viral video product showcase systems.',
      'Strict adherence to US platform fulfillment frameworks ensuring premium seller ranking.'
    ],
    process: [
      'Affiliate Channel Setup & Outreach campaigns',
      'Engaging Video Asset Feed Production',
      'Rapid US Domestic Fulfillment under 72h'
    ]
  },
  {
    id: 'ads-marketing',
    title: 'Meta & ByteDance Paid Acquisition',
    iconName: 'TrendingUp',
    description: 'High-yield customer acquisition frameworks. We create, launch, and monitor creative ad campaigns on Facebook, Instagram, and TikTok, scaling daily returns with rigorous A/B visual testing workflows.',
    details: [
      'Advanced conversion API setups bypass browser cookie limitations sustainably.',
      'Rapid dynamic asset variations testing hundreds of hook-headline matches.',
      'Precise custom and lookalike modeling targeting high-value premium buyers.'
    ],
    process: [
      'Creative Hook & Angle Brainstorming',
      'A/B Asset Testing & Ad Budget Optimization',
      'Dynamic Scaling of Multi-Thousand USD Budgets'
    ]
  }
];

export const JOB_POSITIONS: JobPosition[] = [];

export const MILESTONES: Milestone[] = [
  {
    id: 'summit-2024',
    date: 'October 2024',
    title: 'TikTok Shop US Ecosystem Summit 2024',
    tag: 'Industry Leadership',
    summary: 'Selected as a strategic merchant representative, securing first-hand insights on US platform policies.',
    detail: 'Our executive team was invited to the exclusive TikTok Shop US Ecosystem Summit. The event unlocked direct API betas, previewed fulfillment initiatives, and connected Qnext with primary TikTok US category managers. This keeps our operation ahead on algorithm rules and buyer trends.',
  },
  {
    id: 'bootcamp-2',
    date: 'February 2025',
    title: 'Ecombator TikTok Shop US Bootcamp 2',
    tag: 'Elite Networking',
    summary: 'Engaged with leading international agencies to optimize global dropshipping systems.',
    detail: 'Qnext successfully graduated from the elite Ecombator Bootcamp 2 ecosystem. We presented our high-speed product operational loop, integrated next-generation advertising metrics, and built active logistical partnerships with global distribution facilities.',
  },
  {
    id: 'expansion-2026',
    date: 'Summer 2026',
    title: 'TikTok Shop Team Extension Phase',
    tag: 'Corporate Growth',
    summary: 'Tripling our creative and operational scale to service five brand-new US merchant nodes.',
    detail: 'To support our rapid sales trajectory, we are expanding our physical operations, scaling our creative infrastructure, R&D lines, and ad operations to service brand-new US merchant nodes.',
  }
];

export const PARTNERS: Partner[] = [
  // Merchants
  { name: 'Shopify', logoText: 'S', role: 'Commerce Infrastructure', category: 'ecommerce' },
  { name: 'ShopBase', logoText: 'SB', role: 'Optimized Landing Pages', category: 'ecommerce' },
  { name: 'Ecomdy', logoText: 'E', role: 'TikTok Ads Partner Node', category: 'ecommerce' },
  // Payments
  { name: 'Stripe', logoText: 'St', role: 'US Card Processing Hub', category: 'payment' },
  { name: 'Airwallex', logoText: 'Aw', role: 'Global Multi-Currency virtual cards', category: 'payment' },
  { name: 'PingPong', logoText: 'PP', role: 'Fast Cross-Border Withdrawal', category: 'payment' },
  { name: 'Payoneer', logoText: 'Pn', role: 'Strategic Corporate Banking', category: 'payment' },
  { name: 'PayPal', logoText: 'Py', role: 'Global Buyer Security Terminal', category: 'payment' },
];

export const OFFICES: OfficeAddress[] = [
  {
    country: 'Singapore',
    city: 'Singapore (HQ)',
    name: 'Qnext Pte. Ltd.',
    address: '114 LAVENDER STREET #10-05 CT HUB 2 SINGAPORE 338729',
    email: 'hq@qnextgroup.com',
    phone: '+65 6712 9011',
    coordinates: { x: 35, y: 40 }
  }
];
